### ISSUE TITLE
(Tool issue) aplbrain/i2gseg- neuron segmentation fails when importing scipy

### ISSUE THREAD

**Issue by dxenes1** [aplbrain/saber#18]
Running neuron segmentation with the current dockerfile yields the following error when triggered: 
```
[2019-08-08 14:37:12,269] {docker_operator.py:182} INFO - Starting docker container from image aplbrain/i2gseg:local
[2019-08-08 14:37:15,002] {docker_operator.py:228} INFO - Traceback (most recent call last):
[2019-08-08 14:37:15,003] {docker_operator.py:228} INFO - File "driver.py", line 17, in <module>
[2019-08-08 14:37:15,003] {docker_operator.py:228} INFO - from gala import imio, classify, features, morpho, agglo, evaluate as ev
[2019-08-08 14:37:15,004] {docker_operator.py:228} INFO - File "/gala/gala/features/__init__.py", line 8, in <module>
[2019-08-08 14:37:15,004] {docker_operator.py:228} INFO - from . import \
[2019-08-08 14:37:15,004] {docker_operator.py:228} INFO - File "/gala/gala/features/convex_hull.py", line 8, in <module>
[2019-08-08 14:37:15,005] {docker_operator.py:228} INFO - from scipy.misc import factorial
[2019-08-08 14:37:15,005] {docker_operator.py:228} INFO - ImportError: cannot import name 'factorial'
[2019-08-08 14:37:15,123] {docker_operator.py:228} INFO - Traceback (most recent call last):
[2019-08-08 14:37:15,124] {docker_operator.py:228} INFO - File "/app/localwrap", line 72, in <module>
[2019-08-08 14:37:15,125] {docker_operator.py:228} INFO - raise SystemError('Child process failed with exit code {}... exiting...'.format(proc))
[2019-08-08 14:37:15,125] {docker_operator.py:228} INFO - SystemError: Child process failed with exit code 1... exiting...
[2019-08-08 14:37:15,684] {models.py:1760} ERROR - docker container failed: {'Error': None, 'StatusCode': 1}
```
Seems there is a compatibility issue:
https://github.com/statsmodels/statsmodels/issues/5759

**Comment by dxenes1** [comment]
fixed by pinning scipy version on requirements.txt
